### PR TITLE
Allow for start / end to be optional / nullable for selecting no range

### PR DESCRIPTION
**Pull request by chubbard**
Currently the date range control only allows the user to select a valid date range so the control doesn't support an optional field.  It requires a date range.  Therefore the user can not signify it wants to do some operation that doesn't have a range.  This commit allows for specifying a predefined range that doesn't specify a range.  Please review as I have found some parts of the code that appear to be defects that doesn't not directly pertain to this change.  I'd appreciate any guidance on how we could address the intent of those sections so they are correct.  This should address #18

### CODE REVIEW

**Comment by chubbard** [comment]
This should address #18

**Comment by lucrod1** [comment]
@vlio20 Merge PR please!

**Comment by lucrod1** [comment]
@vlio20 could you generate a new release please

**Comment by Seva42matters** [comment]
@vlio20 indeed, could you? :)

**Pull request merged**
